version: "3.1"

services: 
  mysql:
    image: mysql:5.7.35
    container_name: pauta-mysql
    volumes:
      - ./src/main/resouces/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pauta123
      - MYSQL_DATABASE=dasafiopauta
    ports:
      - "8046:3306"
    expose:
      - '3306'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE